### ISSUE TITLE
Issue running 1.16.5

### ISSUE THREAD

**Issue by NoozAbooz** [pi-dev500/MinecraftMicrosoftPILauncher#6]
```
[14/04/2021 16:22:23 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [/usr/lib/jvm/java-11-openjdk-armhf/bin/java, -XX:-OmitStackTraceInFastThrow, -Xms512M, -Xmx1024M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dorg.lwjgl.librarypath=/home/pi/.local/share/ATlauncher/lwjgl, -XX:+UseConcMarkSweepGC, -XX:-UseAdaptiveSizePolicy, -Xmn128M, -Xss1M, -Djava.library.path=USERSDIR/temp/natives-5a374e7112204356a9b2e5dd5ccc0729, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.3.1, -Djava.library.path=USERSDIR/temp/natives-5a374e7112204356a9b2e5dd5ccc0729, -cp, USERSDIR/libraries/net/minecraft/client/1.16.5/client-1.16.5.jar:USERSDIR/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:USERSDIR/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:USERSDIR/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:USERSDIR/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:USERSDIR/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:USERSDIR/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:USERSDIR/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:USERSDIR/libraries/com/google/guava/guava/21.0/guava-21.0.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:USERSDIR/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:USERSDIR/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:USERSDIR/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:USERSDIR/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:USERSDIR/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:USERSDIR/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:USERSDIR/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:USERSDIR/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:USERSDIR/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:USERSDIR/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:USERSDIR/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar:USERSDIR/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar, net.minecraft.client.main.Main, --username, REDACTED, --version, 1.16.5, --gameDir, USERSDIR/instances/VanillaMinecraft, --assetsDir, USERSDIR/assets, --assetIndex, 1.16, --uuid, 0e03564bf8aa41d7aca52fb76d8171fa, --accessToken, REDACTED, --userType, mojang, --versionType, release, --width=854, --height=480]
[14/04/2021 16:22:23 PM] OpenJDK Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[14/04/2021 16:22:43 PM] [16:22:43] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14/04/2021 16:22:47 PM] [16:22:47] [Render thread/INFO]: Setting user: **MINECRAFTUSERNAME**
[14/04/2021 16:22:48 PM] [16:22:48] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
[14/04/2021 16:22:48 PM] 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
[14/04/2021 16:22:48 PM] 	b) Add the JAR that contains the shared library to the classpath.
[14/04/2021 16:22:48 PM] [16:22:48] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[14/04/2021 16:22:48 PM] [16:22:48] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[14/04/2021 16:22:48 PM] ---- Minecraft Crash Report ----
[14/04/2021 16:22:48 PM] // I blame Dinnerbone.
[14/04/2021 16:22:48 PM] 
[14/04/2021 16:22:48 PM] Time: 4/14/21, 4:22 PM
[14/04/2021 16:22:48 PM] Description: Initializing game
[14/04/2021 16:22:48 PM] 
[14/04/2021 16:22:48 PM] java.lang.ExceptionInInitializerError
[14/04/2021 16:22:48 PM] 	at dkd.<init>(SourceFile:146)
[14/04/2021 16:22:48 PM] 	at djz.<init>(SourceFile:440)
[14/04/2021 16:22:48 PM] 	at net.minecraft.client.main.Main.main(SourceFile:177)
[14/04/2021 16:22:48 PM] Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
[14/04/2021 16:22:48 PM] 	at deo.<clinit>(SourceFile:46)
[14/04/2021 16:22:48 PM] 	... 3 more
[14/04/2021 16:22:48 PM] Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
[14/04/2021 16:22:48 PM] 	at org.lwjgl.system.Library.loadSystem(Library.java:147)
[14/04/2021 16:22:48 PM] 	at org.lwjgl.system.Library.loadSystem(Library.java:67)
[14/04/2021 16:22:48 PM] 	at org.lwjgl.system.Library.<clinit>(Library.java:50)
[14/04/2021 16:22:48 PM] 	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
[14/04/2021 16:22:48 PM] 	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
[14/04/2021 16:22:48 PM] 	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
[14/04/2021 16:22:48 PM] 	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
[14/04/2021 16:22:48 PM] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[14/04/2021 16:22:48 PM] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:357)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:354)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.ClassValue.get(ClassValue.java:114)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:378)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:368)
[14/04/2021 16:22:48 PM] 	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:400)
[14/04/2021 16:22:48 PM] 	at deo.<clinit>(SourceFile:43)
[14/04/2021 16:22:48 PM] 	... 3 more
[14/04/2021 16:22:48 PM] 
[14/04/2021 16:22:48 PM] 
[14/04/2021 16:22:48 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[14/04/2021 16:22:48 PM] ---------------------------------------------------------------------------------------
[14/04/2021 16:22:48 PM] 
[14/04/2021 16:22:48 PM] -- Head --
[14/04/2021 16:22:48 PM] Thread: Render thread
[14/04/2021 16:22:48 PM] Stacktrace:
[14/04/2021 16:22:48 PM] 	at dkd.<init>(SourceFile:146)
[14/04/2021 16:22:48 PM] 	at djz.<init>(SourceFile:440)
[14/04/2021 16:22:48 PM] 
[14/04/2021 16:22:48 PM] -- Initialization --
[14/04/2021 16:22:48 PM] Details:
[14/04/2021 16:22:48 PM] Stacktrace:
[14/04/2021 16:22:48 PM] 	at net.minecraft.client.main.Main.main(SourceFile:177)
[14/04/2021 16:22:49 PM] 
[14/04/2021 16:22:49 PM] -- System Details --
[14/04/2021 16:22:49 PM] Details:
[14/04/2021 16:22:49 PM] 	Minecraft Version: 1.16.5
[14/04/2021 16:22:49 PM] 	Minecraft Version ID: 1.16.5
[14/04/2021 16:22:49 PM] 	Operating System: Linux (arm) version 5.10.17-v8+
[14/04/2021 16:22:49 PM] 	Java Version: 11.0.9.1, Raspbian
[14/04/2021 16:22:49 PM] 	Java VM Version: OpenJDK Server VM (mixed mode), Raspbian
[14/04/2021 16:22:49 PM] 	Memory: 301931160 bytes (287 MB) / 523501568 bytes (499 MB) up to 1060372480 bytes (1011 MB)
[14/04/2021 16:22:49 PM] 	CPUs: 4
[14/04/2021 16:22:49 PM] 	JVM Flags: 8 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx1024M -XX:MetaspaceSize=256M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -Xmn128M -Xss1M
[14/04/2021 16:22:49 PM] 	Launched Version: 1.16.5
[14/04/2021 16:22:49 PM] 	Backend library: LWJGL version 3.2.2 build 10
[14/04/2021 16:22:49 PM] 	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
[14/04/2021 16:22:49 PM] 	GL Caps: 
[14/04/2021 16:22:49 PM] 	Using VBOs: Yes
[14/04/2021 16:22:49 PM] 	Is Modded: Probably not. Jar signature remains and client brand is untouched.
[14/04/2021 16:22:49 PM] 	Type: Client (map_client.txt)
[14/04/2021 16:22:49 PM] 	CPU: <unknown>
[14/04/2021 16:22:49 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**/instances/VanillaMinecraft/crash-reports/crash-2021-04-14_16.22.48-client.txt
[14/04/2021 16:22:49 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[14/04/2021 16:22:49 PM] Checking for updated files!
```

Here's atlauncher:
![image](https://user-images.githubusercontent.com/44128563/114788133-2f2ddc80-9d3e-11eb-8966-be8dfafd423d.png)

Heres the lwjgl3 folder. Note that I use a arm64 kernel but still run a 32-bit userspace.
![image](https://user-images.githubusercontent.com/44128563/114788253-5d132100-9d3e-11eb-98df-4d25b09b1fce.png)

**Comment by pi-dev500** [comment]
For the instant that don't crash for me but i run a arm64 kernel on a 32 bits machine. Your error is weird.

**Comment by pi-dev500** [comment]
#4 for others comments
